# Generated by Django 5.0 on 2024-02-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='win_count',
            new_name='vitorias',
        ),
    ]
